# host
http://localhost:5000/api

# curl options
 --silent
# include response headers
# --include
# to ignore SSL when working with localhost
# --insecure
# to read a header(s) from a file.  File format should be like:

# authorization
# Header-Name: Header-Value
# e.g. Authorization: YOUR_AUTH_TOKEN_HERE
# -H @/path/to/file.txt

# headers
Accept: application/json;
Connection: keep-alive
Content-Type: application/json; charset=utf-8
User-Agent: VRC

# query
# GET /canvas/screen-size
# PATCH /canvas/screen-size/e4b5fa76-b077-4a6a-89c9-58e6e2cd101b/name
PATCH /canvas/screen-size/e4b5fa76-b077-4a6a-89c9-58e6e2cd101b/width
# PATCH /canvas/screen-size/e4b5fa76-b077-4a6a-89c9-58e6e2cd101b/heigth

# body
{
    # "name": "new name"
    "width": "10"
    # "heigth": "10"
}




