# host
http://localhost:5000/api

# curl options
 --silent
# include response headers
# --include
# to ignore SSL when working with localhost
# --insecure
# to read a header(s) from a file.  File format should be like:

# authorization
# Header-Name: Header-Value
# e.g. Authorization: YOUR_AUTH_TOKEN_HERE
# -H @/path/to/file.txt

# headers
Accept: application/json;
Connection: keep-alive
Content-Type: application/json; charset=utf-8
User-Agent: VRC

# query
GET /media-buckets  
# GET /media-buckets/root  
# GET /media-buckets/87a97032-e6cd-4930-8789-7f495ae03da7  

# body
# {
#     "name": "block name",
#     "description": "Hello world",
#     "block_type": "normal_block"
# }
