# host
http://localhost:5000/api

# curl options
 --silent
# include response headers
# --include
# to ignore SSL when working with localhost
# --insecure
# to read a header(s) from a file.  File format should be like:

# authorization
# Header-Name: Header-Value
# e.g. Authorization: YOUR_AUTH_TOKEN_HERE
# -H @/path/to/file.txt

# headers
Accept: application/json;
Connection: keep-alive
Content-Type: application/json; charset=utf-8
User-Agent: VRC

# query
POST  /array/templates

# body
{
    "name": "hello world",
    "array_block_id": "c0667909-0121-4621-a44f-9a5e16b2bcd0",
    "array_block_item_id": "c5d1dcaa-be8f-4e03-8900-247794f96a26"
}
