# host
http://localhost:5000/api

# curl options
 --silent
# include response headers
# --include
# to ignore SSL when working with localhost
# --insecure
# to read a header(s) from a file.  File format should be like:

# authorization
# Header-Name: Header-Value
# e.g. Authorization: YOUR_AUTH_TOKEN_HERE
# -H @/path/to/file.txt

# headers
Accept: application/json;
Connection: keep-alive
Content-Type: application/json; charset=utf-8
User-Agent: VRC

# query
DELETE /canvas/pages/elements/8af32838-56e9-4900-a2b1-64fe4f73c064  


# body
# {
#     "name": "block name",
#     "description": "Hello world",
#     "block_type": "normal_block"
# }
