# host
http://localhost:5000/api

# curl options
 --silent
# include response headers
# --include
# to ignore SSL when working with localhost
# --insecure
# to read a header(s) from a file.  File format should be like:

# authorization
# Header-Name: Header-Value
# e.g. Authorization: YOUR_AUTH_TOKEN_HERE
# -H @/path/to/file.txt

# headers
Accept: application/json;
Connection: keep-alive
Content-Type: application/json; charset=utf-8
User-Agent: VRC

# query
GET /canvas/pages/elements/0075dc57-3471-45ff-b7fa-0404718bf637/html

# body
# {
#     "type": "div",
#     "parentId": null,
#     "styles": {
#     "display": "flex",
#     "flexDirection": "column",
#         "padding": "16px",
#         "backgroundColor": "#f9f9f9"
#     },
#     "content": "",
#     "attributes": {},
#     "order": 0,
#     "name": "MainContainer"
# }
